const friends = [
  {
    id: 1,
    mainIcon: './images/achievement-icon-friends-bronze.png',
    title: "Пригласить друга",
    description: 'Пригласите в игру 1 друга',
    effectIcon: "./images/coin.png",
    effect: 10000,
  },
  {
    id: 2,
    mainIcon: './images/achievement-icon-friends-silver.png',
    title: "Пригласить друга",
    description: 'Пригласите в игру 5 друзей',
    effectIcon: "./images/coin.png",
    effect: 50000,
  },
  {
    id: 3,
    mainIcon: './images/achievement-icon-friends-gold.png',
    title: "Пригласить друга",
    description: 'Пригласите в игру 10 друзей',
    effectIcon: "./images/coin.png",
    effect: 75000,
  },
  {
    id: 4,
    mainIcon: './images/achievement-icon-friends-gold.png',
    title: "Пригласить друга",
    description: 'Пригласите в игру 15 друзей',
    effectIcon: "./images/coin.png",
    effect: 100000,
  },
  {
    id: 5,
    mainIcon: './images/achievement-icon-friends-gold.png',
    title: "Пригласить друга",
    description: 'Пригласите в игру 25 друзей',
    effectIcon: "./images/coin.png",
    effect: 125000,
  },
];
