const friendsTasks = [
  {
    id: 1,
    // mainIcon: './images/achievement-icon-friends-bronze.png',
    mainIcon: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
    title: "Привести друга",
    description: 'Приведите в игру 1 друга',
    effectIcon: "./images/coin.png",
    effect: 10000,
    limit: 1,
  },
  {
    id: 2,
    // mainIcon: './images/achievement-icon-friends-silver.png',
    mainIcon: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
    title: "Привести друга",
    description: 'Приведите в игру 5 друзей',
    effectIcon: "./images/coin.png",
    effect: 50000,
    limit: 5,
  },
  {
    id: 3,
    // mainIcon: './images/achievement-icon-friends-gold.png',
    mainIcon: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
    title: "Привести друга",
    description: 'Приведите в игру 10 друзей',
    effectIcon: "./images/coin.png",
    effect: 75000,
    limit: 10,
  },
  {
    id: 4,
    // mainIcon: './images/achievement-icon-friends-gold.png',
    mainIcon: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
    title: "Привести друга",
    description: 'Приведите в игру 15 друзей',
    effectIcon: "./images/coin.png",
    effect: 100000,
    limit: 15,
  },
  {
    id: 5,
    // mainIcon: './images/achievement-icon-friends-gold.png',
    mainIcon: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
    title: "Привести друга",
    description: 'Приведите в игру 25 друзей',
    effectIcon: "./images/coin.png",
    effect: 125000,
    limit: 25,
  },
];
